'use client';

import { Suspense, useEffect, useState } from 'react';
import { useSearchParams } from 'next/navigation';
import LZString from 'lz-string';
import { Dashboard } from '@/components/dashboard';
import { ATSInsights } from '@/components/ats-insights';
import { Container } from '@/components/ui/container';
import { ResumeAnalysis, ATSAnalysis } from '@/ai/schema';
import { Loader2 } from 'lucide-react';

function ShareReportContent() {
    const searchParams = useSearchParams();
    const [data, setData] = useState<{ analysis: ResumeAnalysis; atsAnalysis: ATSAnalysis } | null>(null);
    const [error, setError] = useState<string | null>(null);

    useEffect(() => {
        const payload = searchParams.get('data');
        if (payload) {
            try {
                const decompressed = LZString.decompressFromEncodedURIComponent(payload);
                if (decompressed) {
                    const parsed = JSON.parse(decompressed);
                    setData(parsed);
                } else {
                    setError('Invalid or corrupted link. Cannot load shared report.');
                }
            } catch (e) {
                console.error('Failed to parse shared data', e);
                setError('Failed to load shared report.');
            }
        } else {
            setError('No data found in URL.');
        }
    }, [searchParams]);

    if (error) {
        return (
            <div className="text-center py-24">
                <p className="text-destructive font-medium">{error}</p>
                <p className="text-muted-foreground mt-2 text-sm">Please ask the sender for a new link.</p>
            </div>
        );
    }

    if (!data) {
        return (
            <div className="flex flex-col items-center justify-center py-24">
                <Loader2 className="h-8 w-8 animate-spin text-primary" />
                <p className="mt-4 text-muted-foreground text-sm">Loading shared report...</p>
            </div>
        );
    }

    return (
        <div className="space-y-12 pb-12">
            <div>
                <h2 className="text-2xl font-bold border-b pb-2 mb-6 text-primary">Content Analysis</h2>
                <Dashboard analysis={data.analysis} />
            </div>
            <div className="pt-8">
                <h2 className="text-2xl font-bold border-b pb-2 mb-6 text-primary">ATS Insights</h2>
                <ATSInsights analysis={data.atsAnalysis} />
            </div>
        </div>
    );
}

export default function SharePage() {
    return (
        <div className="flex flex-col min-h-screen">
            <main className="flex-1 py-12 md:py-24">
                <Container className="max-w-5xl space-y-8">
                    <div className="text-center max-w-2xl mx-auto space-y-2 print:hidden mb-12">
                        <h1 className="text-3xl font-bold tracking-tight">Shared Resume Report</h1>
                        <p className="text-muted-foreground">
                            This report was generated by AI Resume Analyzer.
                        </p>
                    </div>

                    <Suspense fallback={
                        <div className="flex flex-col items-center justify-center py-24">
                            <Loader2 className="h-8 w-8 animate-spin text-primary" />
                        </div>
                    }>
                        <ShareReportContent />
                    </Suspense>

                </Container>
            </main>
        </div>
    );
}
